<#
.SYNOPSIS
  Finds FormWorks/DCM managed and native DLLs and prepares the x86 workbench layout.

.DESCRIPTION
  Expected local layout after this script:

      .\lib      managed .NET wrapper DLLs: rrifwd_net.dll, rribase_net.dll, etc.
      .\rri_bin  native 32-bit DLLs: rrifwd.dll, rribase.dll, etc.

  Native DLLs belong in rri_bin, not lib. The generated runtime-path.generated.ps1 only
  prepends rri_bin to PATH.
#>
[CmdletBinding()]
param(
    [string]$HarnessRoot = '',
    [string]$RriRoot = '',
    [string]$DcmBinRoot = 'C:\rri\ddce\bin',
    [switch]$CopyNative,
    [switch]$PreferNewest
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$scriptRoot = if (-not [string]::IsNullOrWhiteSpace($PSScriptRoot)) { $PSScriptRoot } else { Split-Path -Parent $PSCommandPath }
if ([string]::IsNullOrWhiteSpace($HarnessRoot)) { $HarnessRoot = (Resolve-Path -LiteralPath (Join-Path $scriptRoot '..')).Path }
if ([string]::IsNullOrWhiteSpace($RriRoot)) { $RriRoot = Join-Path $HarnessRoot 'rri_bin' }

function Write-Section([string]$Text) { Write-Host ''; Write-Host $Text -ForegroundColor Cyan; Write-Host ('=' * $Text.Length) -ForegroundColor DarkCyan }

function Find-OneDll {
    param(
        [Parameter(Mandatory = $true)][string[]]$Root,
        [Parameter(Mandatory = $true)][string]$Name,
        [switch]$Newest
    )
    $items = @()
    foreach ($candidateRoot in $Root) {
        if (Test-Path -LiteralPath $candidateRoot) {
            $items += @(Get-ChildItem -Path $candidateRoot -Recurse -Filter $Name -File -ErrorAction SilentlyContinue)
        }
    }
    if ($items.Count -eq 0) { return $null }
    if ($Newest) { return $items | Sort-Object LastWriteTime -Descending | Select-Object -First 1 }
    $preferred = $items | Where-Object { $_.FullName -match 'R2023Q3' -and $_.FullName -match 'SP1' } | Select-Object -First 1
    if ($preferred) { return $preferred }
    return $items | Select-Object -First 1
}

$managedDlls = @('rribase_net.dll', 'rrifwd_net.dll', 'rridc_net.dll', 'rriwf2_net.dll', 'FormWorks.Core.dll', 'FormWorks.Versioning.dll')
$nativeDlls = @('rribase.dll', 'rrifwd.dll', 'rridc.dll', 'rriwf2.dll')

$libDir = Join-Path $HarnessRoot 'lib'
$repoRriBin = Join-Path $HarnessRoot 'rri_bin'
New-Item -ItemType Directory -Force -Path $libDir | Out-Null
New-Item -ItemType Directory -Force -Path $repoRriBin | Out-Null

$managedSearchRoots = @($libDir, $repoRriBin, $RriRoot, $DcmBinRoot) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique
$nativeSearchRoots = @($repoRriBin, $RriRoot, $DcmBinRoot) | Where-Object { -not [string]::IsNullOrWhiteSpace($_) } | Select-Object -Unique

Write-Section 'Copying managed .NET DLLs to lib'
$missingManaged = New-Object System.Collections.Generic.List[string]
foreach ($dll in $managedDlls) {
    $found = Find-OneDll -Root $managedSearchRoots -Name $dll -Newest:$PreferNewest
    if (-not $found) { $missingManaged.Add($dll); Write-Host "MISSING: $dll" -ForegroundColor Red; continue }
    $dest = Join-Path $libDir $dll
    Copy-Item -LiteralPath $found.FullName -Destination $dest -Force
    Write-Host "Copied $dll" -ForegroundColor Green
    Write-Host "  from: $($found.FullName)" -ForegroundColor DarkGray
    Write-Host "  to  : $dest" -ForegroundColor DarkGray
}

Write-Section 'Finding native 32-bit DLLs'
$missingNative = New-Object System.Collections.Generic.List[string]
foreach ($dll in $nativeDlls) {
    $found = Find-OneDll -Root $nativeSearchRoots -Name $dll -Newest:$PreferNewest
    if (-not $found) { $missingNative.Add($dll); Write-Host "MISSING: $dll" -ForegroundColor Red; continue }
    Write-Host "Found $dll" -ForegroundColor Green
    Write-Host "  at: $($found.FullName)" -ForegroundColor DarkGray
    if ($CopyNative -or $found.DirectoryName -ne $repoRriBin) {
        Copy-Item -LiteralPath $found.FullName -Destination (Join-Path $repoRriBin $dll) -Force
        Write-Host "  copied to: $repoRriBin" -ForegroundColor DarkGray
    }
}

$runtimePathScript = Join-Path $scriptRoot 'runtime-path.generated.ps1'
$escapedNativeDir = $repoRriBin.Replace("'", "''")
@"
# Auto-generated by setup-dcm-deps.ps1.
# Native FormWorks/DCM DLLs are loaded from the 32-bit rri_bin folder.
`$NativeLibDir = '$escapedNativeDir'
if (-not (Test-Path -LiteralPath `$NativeLibDir)) {
    throw "Native FormWorks runtime folder not found: `$NativeLibDir"
}
`$currentPath = [Environment]::GetEnvironmentVariable('PATH', 'Process')
`$pathParts = @(`$currentPath -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace(`$_) })
if (`$pathParts -notcontains `$NativeLibDir) {
    [Environment]::SetEnvironmentVariable('PATH', "`$NativeLibDir;`$currentPath", 'Process')
    `$env:PATH = [Environment]::GetEnvironmentVariable('PATH', 'Process')
}
`$env:FORMWORKS_NATIVE_BIN = `$NativeLibDir
`$env:ACRULEWORKBENCH_PLATFORM = 'x86'
"@ | Set-Content -LiteralPath $runtimePathScript -Encoding UTF8 -Force

Write-Section 'Summary'
Write-Host "Harness root: $HarnessRoot"
Write-Host "Managed lib : $libDir"
Write-Host "Native bin  : $repoRriBin"
Write-Host "PATH helper : $runtimePathScript"

if ($missingManaged.Count -gt 0) { Write-Host "Missing managed DLLs: $($missingManaged -join ', ')" -ForegroundColor Red }
if ($missingNative.Count -gt 0) { Write-Host "Missing native DLLs: $($missingNative -join ', ')" -ForegroundColor Red }
if ($missingManaged.Count -gt 0 -or $missingNative.Count -gt 0) { exit 2 }

Write-Host 'Setup complete. Next: .\scripts\build-and-doctor.ps1' -ForegroundColor Green
